// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"
)

type Chat struct {
	ID int64 `json:"id"`
	// The from/to order makes no difference here
	FromUserID int64 `json:"from_user_id"`
	// The from/to order makes no difference here
	ToUserID              int64        `json:"to_user_id"`
	LastMessageReceivedAt sql.NullTime `json:"last_message_received_at"`
}

type Contact struct {
	ID int64 `json:"id"`
	// The from/to order makes no difference here
	FromUserID int64 `json:"from_user_id"`
	// The from/to order makes no difference here
	ToUserID int64 `json:"to_user_id"`
	// Pending, Accepted or Rejected
	Status      string       `json:"status"`
	RequestedAt time.Time    `json:"requested_at"`
	AcceptedAt  sql.NullTime `json:"accepted_at"`
}

type Message struct {
	ID         int64     `json:"id"`
	ChatID     int64     `json:"chat_id"`
	FromUserID int64     `json:"from_user_id"`
	ToUserID   int64     `json:"to_user_id"`
	Body       string    `json:"body"`
	SentAt     time.Time `json:"sent_at"`
}

type User struct {
	ID                int64          `json:"id"`
	CreatedAt         time.Time      `json:"created_at"`
	FullName          string         `json:"full_name"`
	Username          string         `json:"username"`
	Email             sql.NullString `json:"email"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	LastLoginAt       sql.NullTime   `json:"last_login_at"`
	HashPass          string         `json:"hash_pass"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
}
