// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	AcceptContact(ctx context.Context, id int64) (Contact, error)
	ChangeUserPassword(ctx context.Context, arg ChangeUserPasswordParams) (User, error)
	CheckExistingContact(ctx context.Context, arg CheckExistingContactParams) ([]Contact, error)
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteChat(ctx context.Context, id int64) error
	DeleteContact(ctx context.Context, id int64) error
	DeleteMessage(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetChat(ctx context.Context, id int64) (Chat, error)
	GetChatByUserIDs(ctx context.Context, arg GetChatByUserIDsParams) (Chat, error)
	GetContact(ctx context.Context, id int64) (Contact, error)
	GetMessage(ctx context.Context, id int64) (Message, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAcceptedContacts(ctx context.Context, arg ListAcceptedContactsParams) ([]Contact, error)
	ListChats(ctx context.Context, arg ListChatsParams) ([]Chat, error)
	ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error)
	ListPendingContacts(ctx context.Context, arg ListPendingContactsParams) ([]Contact, error)
	ListRejectedContacts(ctx context.Context, arg ListRejectedContactsParams) ([]Contact, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	RejectContact(ctx context.Context, id int64) (Contact, error)
	UpdateChat(ctx context.Context, id int64) (Chat, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
